name: CI
on:
  push:
    branches:
      - main
    tags:
      - "v*"
permissions:
  contents: write

jobs:
  #check if tag from package.json version exist if not create new tag
  check_tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
      - name: Install dependencies
        run: npm install
      - name: Check tag
        id: check_tag
        run: |
          echo "Checking if tag exists"
          if git rev-parse "v$(node -p "require('./package.json').version")" >/dev/null 2>&1
          then
            echo "Tag exists"
            echo "name=tag_exists::true" >> $GITHUB_OUTPUT
          else
            echo "Tag does not exist"
            echo "name=tag_exists::false" >> $GITHUB_OUTPUT
          fi
      - name: Create tag
        if: steps.check_tag.outputs.tag_exists == false
        run: |
          echo "Creating tag"
          git tag "v$(node -p "require('./package.json').version")"
          git push --tags

  build_on_linux:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: release/*/*
          draft: true
          prerelease: true
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ github.ref }}
          name: ${{ github.ref }}
          body: ${{ github.ref }}
  builds_on_win:
    runs-on: windows-latest
    # check if on tag
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: release/*/*
          draft: true
          prerelease: true
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ github.ref }}
          name: ${{ github.ref }}
          body: ${{ github.ref }}

  # commit draft
  release:
    runs-on: ubuntu-latest
    needs: [build_on_linux, builds_on_win]
    steps:
      - uses: actions/checkout@master
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: release/*/*
          draft: false
          prerelease: true
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ github.ref }}
          name: ${{ github.ref }}
          body: ${{ github.ref }}
